version: '3'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      # Config server
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
      - SPRING_CLOUD_CONFIG_PASSWORD=${SPRING_CLOUD_CONFIG_PASSWORD}
      # Eureka config
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - EUREKA_INSTANCE_HOSTNAME= ${EUREKA_INSTANCE_HOSTNAME}
      - EUREKA_INSTANCE_IP_ADDRESS= ${EUREKA_INSTANCE_IP_ADDRESS}
      # Gateway config
      # 1. eureka route
      - EUREKA_SERVER_URL= ${EUREKA_SERVER_URL}
      - EUREKA_BASIC_AUTH= ${EUREKA_BASIC_AUTH}
    ports:
      - "8080:8080"  # Gateway public port
    restart: always
